version: '3.8'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 5d & wait $${!}; done;'"
    networks:
      - defaulf
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /home/alex/projects/Billing/static:/var/www/billing/static:ro
      - /home/alex/projects/OnlineChat/static:/var/www/onlinechat/static:ro
      - /home/alex/projects/OnlineChat/media:/var/www/onlinechat/media:ro
      - /home/alex/projects/AlexFireChat/static:/var/www/django/static:ro
      - /home/alex/projects/AlexFireChat/media:/var/www/django/media:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - defaulf
    restart: unless-stopped

networks:
  defaulf:
    driver: bridge